### ISSUE TITLE
Bug report: tmux is recognized as terminal when using it

### ISSUE THREAD

**Issue by NTBBloodbath** [NTBBloodbath/lcfetch#1]
This is caused because of how lcfetch gets the terminal name right now, maybe we should run an additional step for getting tmux PID and then using it for finally reaching the terminal name?

**Comment by NTBBloodbath** [comment]
I think this can also happen when using [zellij](https://github.com/zellij-org/zellij), less popular than tmux but it's widely used too _at least I use it instead of tmux, or I try to_

**Comment by pocco81** [comment]
Can confirm the issue is occurring with tmux.

**Comment by NTBBloodbath** [comment]
This should be fixed now, we are using Xlib for getting the active window instead of the PPids approach.

Note that getting the active window can bring a new bug if you change the current window before lcfetch gets the terminal window stuff but that's other beast that will need to be refactored later
